let old_pearls = [
    "Nel tuo sguardo trovo il mio rifugio sicuro.",
    "Amarti è la melodia che il mio cuore canta.",
    "Sei il mio faro nelle notti buie.",
    "Amarti è la mia ragione di sorridere ogni giorno.",
    "Tu ed io, insieme per l'eternità.",
    "La tua dolcezza mi scioglie il cuore.",
    "Sei la risposta a tutte le mie preghiere.",
    "Nessuna distanza può separare i nostri cuori.",
    "Le tue carezze sono come balsamo per l'anima.",
    "Siamo come una favola, con un lieto fine garantito.",
    "Sei la costante nei miei pensieri.",
    "Ogni momento con te è un regalo.",
    "In ogni tuo gesto trovo amore e gentilezza.",
    "Il nostro amore è una poesia senza fine.",
    "Il mondo diventa più bello quando sei accanto a me.",
    "Le tue parole dolci fanno danzare il mio cuore.",
    "Amarti è come respirare, essenziale per la vita.",
    "Sei la nota dolce nella sinfonia della mia vita.",
    "Il tuo amore è il mio porto sicuro in ogni tempesta.",
    "Sei il mio sogno che è diventato realtà.",
    "Il tuo amore è la mia fonte di felicità infinita.",
    "Ogni istante con te è un momento prezioso da conservare.",
    "Innamorarsi di te è stata la mia migliore avventura.",
    "Sei l'unico pensiero che occupa la mia mente.",
    "La tua bellezza è radiante come il sole all'alba.",
    "Il tuo sorriso fa brillare anche il giorno più grigio.",
    "Ogni tua parola è una carezza per il mio cuore.",
    "I tuoi occhi raccontano la storia del nostro amore.",
    "Sei il mio rifugio sicuro, il mio porto tranquillo.",
    "Amarti è la poesia che il mio cuore non smette di scrivere.",
    "Nel tuo abbraccio trovo calore e consolazione.",
    "Sei la parte di me che non sapevo di cercare.",
    "Ogni tua risata è una melodia dolce che mi incanta.",
    "Il nostro amore cresce ogni giorno come un giardino fiorito.",
    "Le tue mani sono intrecciate con le mie nella trama del destino.",
    "Sei il compagno di viaggio dei miei sogni e speranze.",
    "Nella tua presenza, il tempo sembra fermarsi.",
    "Amarti è come guardare le stelle, un'esperienza magica.",
    "Il nostro amore è la nota dolce nella sinfonia dell'universo.",
    "Sei la mia personale opera d'arte.",
    "Il tuo sorriso è il mio raggio di sole preferito.",
    "Amarti è come un viaggio senza fine.",
    "Sei il mio porto sicuro in ogni tempesta.",
    "La tua gentilezza mi ruba il cuore ogni giorno.",
    "Ogni tuo abbraccio è una cura per l'anima.",
    "Amarti è come leggere la più bella poesia.",
    "Sei la mia ispirazione costante.",
    "Nel tuo sguardo trovo la mia casa.",
    "Il tuo amore è il mio segreto più dolce.",
    "Ogni tua risata è una melodia che mi fa sorridere.",
    "Sei la mia realtà più bella.",
    "Amarti è come ascoltare una melodia delicata.",
    "Nel tuo abbraccio trovo calore e felicità.",
    "Sei la parte di me che completa il puzzle della vita.",
    "Ogni tuo bacio è un desiderio che si avvera.",
    "Amarti è come danzare sotto la pioggia.",
    "Sei il mio faro nella notte più oscura.",
    "La tua presenza è il mio regalo preferito.",
    "Ogni tuo gesto d'amore è una promessa.",
    "Sei il mio angelo custode sulla terra.",
    "Amarti è come esplorare mondi sconosciuti.",
    "Nel tuo sorriso trovo la forza di affrontare tutto.",
    "Sei la mia fortuna e il mio desiderio.",
    "Il tuo amore è il mio combustibile quotidiano.",
    "Amarti è il mio destino e la mia scelta.",
    "Sei la chiave per il mio cuore.",
    "Ogni giorno con te è un'opportunità per amare di più.",
    "Sei il mio confidente più fidato.",
    "Il tuo sorriso è il mio antidoto per qualsiasi tristezza.",
    "Amarti è come guardare un tramonto infinito.",
    "Nel tuo abbraccio trovo conforto e tranquillità.",
    "Sei la poesia che il mio cuore continua a scrivere.",
    "Il tuo amore è il mio bene più prezioso.",
    "Amarti è come sognare ad occhi aperti.",
    "Sei la mia priorità numero uno.",
    "Ogni tuo sguardo è un messaggio d'amore.",
    "Nel tuo amore trovo la mia forza.",
    "Il tuo sorriso illumina la mia giornata.",
    "Sei il mio sogno diventato realtà.",
    "Ogni istante con te è prezioso.",
    "La tua presenza rende tutto migliore.",
    "Insieme, ogni momento è magico.",
    "Nel tuo sguardo trovo il mio rifugio.",
    "Sei la melodia che il mio cuore canta.",
    "Amarti è la cosa più dolce che conosca.",
    "Tu ed io, un destino scritto nelle stelle.",
    "La tua voce è la mia canzone preferita.",
    "Con te ogni giorno è San Valentino.",
    "Sei la parte migliore di me.",
    "Il tuo amore è la mia ispirazione quotidiana.",
    "Nel tuo abbraccio trovo il mio rifugio sicuro.",
    "Sei il mio partner nel crimine dell'amore.",
    "Amarti è come trovare il tesoro nascosto.",
    "Il tuo sorriso rende ogni giorno speciale.",
    "Sei il mio faro guida nella vita.",
    "La tua gentilezza tocca il mio cuore in modi unici.",
    "Amarti è come seguire una stella cadente.",
    "Nel tuo abbraccio trovo consolazione e pace.",
    "Sei la mia risposta a ogni domanda.",
    "Il tuo amore è il mio rifugio sicuro.",
    "Amarti è il sogno che non voglio mai svegliare.",
    "Sei il mio sole quando il cielo è nuvoloso.",
    "Amarti è come osservare una notte stellata.",
    "Sei il mio faro nella tempesta.",
    "Nel tuo abbraccio trovo protezione e amore.",
    "Il tuo sorriso è il mio raggio di luce preferito.",
    "Amarti è come scrivere poesie all'infinito.",
    "Sei il mio sogno che si è trasformato in realtà.",
    "Nel tuo amore trovo conforto e consolazione.",
    "Ogni tuo gesto è un promemoria del tuo amore.",
    "Sei la mia bussola nella selva della vita.",
    "La tua gentilezza rende il mondo un posto migliore.",
    "Nel tuo sguardo trovo la mia pace interiore.",
    "Sei la mia fonte di ispirazione continua.",
    "Il tuo amore è la melodia nella mia anima.",
    "Amarti è come danzare al ritmo dei nostri cuori.",
    "Sei il mio riflesso in ogni sorriso.",
    "Nel tuo abbraccio trovo la mia casa.",
    "La tua voce è la melodia che canta il mio cuore.",
    "Amarti è come gustare il dolce sapore della vita.",
    "Sei il mio porto sicuro in ogni mare agitato.",
    "Nel tuo amore trovo la forza di superare ogni ostacolo.",
    "Sei la mia fiamma che non si spegne mai.",
    "Amarti è come sfogliare pagine di un libro d'amore.",
    "Sei il mio partner nel viaggio della vita.",
    "Nel tuo sorriso trovo la felicità infinita.",
    "Il tuo amore è la poesia che il mio cuore recita.",
    "Amarti è come sentire il calore del sole sulla pelle.",
    "Sei il mio rifugio in ogni momento difficile.",
    "Nel tuo abbraccio trovo il mio paradiso.",
    "La tua gentilezza è la luce che illumina il mio cammino.",
    "Sei la mia speranza nei giorni più bui.",
    "Amarti è come guardare il mondo attraverso occhi innamorati.",
    "Sei il mio segreto più prezioso.",
    "Nel tuo amore trovo la pace che ho sempre cercato.",
    "Il tuo sorriso è la mia medicina contro ogni male.",
    "Amarti è come essere cullati dalle onde dell'amore.",
    "Sei la stella che guida i miei sogni.",
    "Nel tuo sguardo trovo la mia direzione.",
    "La tua presenza è il mio regalo quotidiano.",
    "Amarti è come osservare un tramonto mozzafiato.",
    "Sei la mia luce nella notte più buia.",
    "Nel tuo abbraccio trovo la tranquillità che desidero.",
    "Il tuo amore è la forza che mi fa andare avanti.",
    "Amarti è come risolvere un enigma meraviglioso.",
    "Sei la melodia che accompagna ogni mio passo.",
    "Nel tuo amore trovo la dolcezza che lenisce il cuore.",
    "Sei il mio rifugio nei giorni di pioggia.",
    "Amarti è come creare arte con ogni istante trascorso insieme.",
    "Nel tuo sorriso trovo la felicità senza fine.",
    "Amarti è come vedere il mondo attraverso occhi incantati.",
    "Sei la mia oasi di pace nel deserto della vita.",
    "Nel tuo abbraccio trovo il calore che mi ristora.",
    "Amarti è come ascoltare una melodia celestiale.",
    "Sei la mia guida in ogni passo del cammino.",
    "Nel tuo amore trovo la gioia che alimenta il mio spirito.",
    "Amarti è come scoprire un tesoro nascosto.",
    "Sei il mio rifugio sicuro dal caos del mondo.",
    "Nel tuo sguardo trovo l'amore che mi completa.",
    "Il tuo amore è il mio elisir di vita.",
    "Amarti è come sorseggiare il vino più pregiato.",
    "Sei la mia costante fonte di felicità.",
    "Nel tuo amore trovo la certezza di un domani migliore.",
    "Amarti è come viaggiare verso l'infinito.",
    "Sei la mia stella polare nella notte.",
    "Nel tuo abbraccio trovo la pace che cerco.",
    "Amarti è come sentire il vento accarezzare la pelle.",
    "Sei il mio complice in ogni avventura.",
    "Amarti è come danzare in armonia con l'universo.",
    "Sei la mia roccia in ogni momento di bisogno.",
    "Nel tuo sorriso trovo la gioia che illumina i miei giorni.",
    "Il tuo amore è la melodia che suona nel mio cuore.",
    "Amarti è come immergersi in un mare di emozioni.",
    "Sei il mio rifugio sicuro da ogni tempesta.",
    "Nel tuo amore trovo il conforto che cerco.",
    "Amarti è come esplorare un giardino segreto.",
    "Sei il mio faro guida in ogni scelta.",
    "Nel tuo abbraccio trovo la forza per affrontare tutto.",
    "Il tuo amore è la poesia che colora la mia vita.",
    "Amarti è come leggere una storia d'amore senza fine.",
    "Sei la mia stella cadente che avvera i desideri.",
    "Nel tuo amore trovo la certezza di un futuro luminoso.",
    "Sei il mio sogno che si realizza ogni giorno.",
    "Nel tuo sorriso trovo la bellezza del mondo.",
    "Il tuo amore è la luce che guida il mio cammino.",
    "Amarti è come scoprire una nuova dimensione.",
    "Sei la mia melodia preferita in ogni stagione.",
    "Nel tuo amore trovo la pace che cercavo.",
    "Amarti è come seguire una mappa verso la felicità.",
    "Sei il mio complice nei giorni di pioggia.",
    "Nel tuo abbraccio trovo il rifugio perfetto.",
    "Il tuo amore è la canzone che canta il mio cuore.",
    "Amarti è come risolvere un enigma avvincente.",
    "Sei la luce che illumina i miei giorni.",
    "Nel tuo amore trovo il conforto che desidero.",
    "Amarti è come un viaggio emozionante.",
    "Sei il mio faro nella notte oscura.",
    "Nel tuo sorriso trovo la dolcezza del paradiso.",
    "Il tuo amore è la poesia che scrivo ogni giorno.",
    "Amarti è come immergersi in un oceano di felicità.",
    "Sei la mia stella polare in un cielo senza fine.",
    "Nel tuo amore trovo la gioia che completa la mia anima.",
    "Amarti è come scoprire il tesoro più prezioso.",
    "Sei il mio rifugio sicuro in ogni momento.",
    "Nel tuo sguardo trovo l'amore che mi riscalda.",
    "Il tuo amore è la melodia che suona nei miei sogni.",
    "Amarti è come viaggiare in un mondo di emozioni.",
    "Sei il mio faro guida nel mare della vita.",
    "Nel tuo amore trovo la pace che cerco.",
    "Amarti è come sentire il battito del mio cuore.",
    "Sei il mio sogno che si avvera ogni giorno.",
    "Nel tuo sorriso trovo la bellezza che mi ispira.",
    "Il tuo amore è la luce che illumina i miei giorni.",
    "Amarti è come leggere poesie d'amore all'infinito.",
    "Sei il mio rifugio sicuro in ogni tempesta.",
    "Nel tuo amore trovo la serenità che desidero.",
    "Amarti è come un viaggio verso l'infinito.",
    "Sei la mia stella polare in un cielo sereno.",
    "Amarti è come danzare sotto la pioggia di emozioni.",
    "Sei il mio rifugio nelle giornate difficili.",
    "Nel tuo amore trovo la felicità che desidero.",
    "Sei il mio faro guida nelle tempeste della vita.",
    "Il tuo amore è la melodia che canta nel mio cuore.",
    "Amarti è come immergersi in un mare di felicità.",
    "Sei il mio rifugio sicuro in ogni mare agitato.",
    "Nel tuo abbraccio trovo calore e conforto.",
    "Amarti è come sentire la dolce brezza dell'amore.",
    "Amarti è come danzare sotto la luna piena.",
    "Sei la mia guida in ogni passo che faccio.",
    "Nel tuo abbraccio trovo la pace che mi manca.",
    "Nel tuo amore trovo la serenità che cerco.",
    "Il tuo amore è il mio porto sicuro.",
    "Nel tuo sguardo trovo un mondo in cui perdermi ogni giorno.",
    "Il tuo amore è come un faro che illumina costantemente la mia strada.",
    "Amarti è come riscoprire il significato profondo dell'affetto.",
    "Sei la mia ispirazione a scrivere nuove pagine della nostra storia.",
    "Ogni tuo sorriso è un'arte che impreziosisce la mia vita.",
    "Nel calore del tuo abbraccio trovo il mio rifugio perfetto.",
    "Le tue parole dolci sono melodie che risuonano nel mio cuore.",
    "Amarti è come ritrovare pezzi mancanti del mio puzzle interiore.",
    "Con te, ogni giorno è un capitolo unico del nostro racconto d'amore.",
    "Sei il mio equilibrio, la calma nel caos della vita.",
    "Il tuo amore è la chiave che apre le porte del mio cuore.",
    "Nel tuo abbraccio sento il battito sincero del tuo amore.",
    "Amarti è come guardare un'opera d'arte in continua evoluzione.",
    "La tua voce è il suono più dolce che il mio cuore possa udire.",
    "Nel tuo amore trovo la forza di superare qualsiasi sfida.",
    "Ogni momento con te è un dono prezioso che custodisco.",
    "Amarti è come camminare su nuvole leggere e incorporee.",
    "Sei la poesia che danza tra le pagine della mia esistenza.",
    "Nel riflesso dei tuoi occhi vedo il futuro che costruiamo insieme.",
    "Il tuo amore è come un balsamo che lenisce ogni ferita.",
    "Nel tuo abbraccio trovo il calore di mille soli.",
    "Il tuo amore è la melodia che accompagna ogni mio passo.",
    "Amarti è come osservare un cielo stellato di emozioni.",
    "Sei la nota dolce nella sinfonia della mia esistenza.",
    "Nel tuo sguardo vedo un universo di possibilità.",
    "Il tuo sorriso è la chiave che sblocca il mio cuore.",
    "Amarti è come trovare un tesoro nascosto nel mio destino.",
    "Sei la luce che dissipa le ombre della mia solitudine.",
    "Nel calore del tuo abbraccio trovo conforto infinito.",
    "Il tuo amore è il vento che spinge le vele dei miei sogni.",
    "Amarti è come leggere pagine di felicità scritte a mano.",
    "Sei il motivo per cui il sole sorride ogni mattina.",
    "Nel tuo amore trovo la risposta a ogni mio perché.",
    "La tua voce è la melodia che canta dolcemente nella mia mente.",
    "Amarti è come trovare il pezzo mancante del mio puzzle.",
    "Sei il riflesso dei miei desideri più profondi.",
    "Nel tuo sguardo vedo un mondo di amore senza fine.",
    "Il tuo sorriso è la luce che illumina i giorni grigi.",
    "Amarti è come scrivere una storia senza fine insieme.",
    "Sei la poesia che rende magico ogni istante della mia vita.",
    "Nel tuo sguardo vedo riflessa l'eternità del nostro amore.",
    "Il tuo sorriso è come un faro che illumina i giorni bui.",
    "Amarti è come perdersi in un labirinto di emozioni profonde.",
    "Sei la risposta alle mie preghiere, il desiderio del mio cuore.",
    "Nel tuo abbraccio trovo il conforto che cerco ogni giorno.",
    "Il tuo amore è la melodia che accompagna ogni risveglio.",
    "Amarti è come danzare al ritmo dolce della nostra connessione.",
    "Sei il mio rifugio sicuro nei momenti di incertezza.",
    "Nel calore del tuo amore trovo la forza di superare ogni ostacolo.",
    "Il tuo sorriso è la luce che illumina il buio della mia anima.",
    "Amarti è come guardare un cielo notturno pieno di stelle.",
    "Sei il mio compagno di viaggio in questa avventura chiamata vita.",
    "Nel tuo abbraccio trovo la calma che cercavo ovunque.",
    "Il tuo amore è la poesia che sussurra dolcemente al mio cuore.",
    "Amarti è come sentirsi al sicuro anche nelle tempeste.",
    "Sei il mio sogno divenuto realtà, la mia realtà più bella.",
    "Nel riflesso dei tuoi occhi vedo il mio futuro radioso.",
    "Il tuo sorriso è il faro che guida la mia navigazione.",
    "Amarti è come scrivere versi di passione nell'eternità.",
    "Sei la melodia costante che suona nella sinfonia della mia vita.",
    "Nel tuo abbraccio trovo rifugio dall'incessante mondo esterno.",
    "Il tuo amore è come un dipinto che colora la mia esistenza.",
    "Amarti è come esplorare le profondità del mio cuore.",
    "Sei la luce che illumina ogni angolo buio della mia mente.",
    "Nel calore del tuo abbraccio trovo la serenità che cerco.",
    "Il tuo sorriso è la chiave che apre le porte del paradiso.",
    "Amarti è come osservare il tramonto, un'opera d'arte unica.",
    "Sei la poesia che danza leggera nel vento del nostro amore.",
    "Nel tuo amore trovo la certezza di un domani radioso.",
    "Il tuo abbraccio è la protezione che scaccia ogni paura.",
    "Amarti è come completare un puzzle di cuori intrecciati.",
    "Sei il mio faro nella notte, la guida del mio cammino.",
    "Nel calore dei tuoi baci trovo la dolcezza che desidero.",
    "Il tuo amore è la melodia che risuona nei miei sogni.",
    "Amarti è come raccogliere conchiglie lungo la spiaggia del tempo.",
    "Sei il mio rifugio sicuro, la salvezza nei giorni difficili.",
    "Nel tuo sguardo vedo il futuro che costruiamo insieme.",
    "Il tuo sorriso è il sole che illumina le mie giornate.",
    "Amarti è come scrivere pagine di felicità nel libro della vita.",
    "Sei la stella che brilla nel cielo buio della mia esistenza.",
    "Il tuo amore è come una brezza leggera che accarezza la mia anima.",
    "Amarti è come vivere un sogno incantato ogni giorno.",
    "Sei la costante che dà ritmo alla melodia del mio cuore.",
    "Nel tuo sguardo trovo la risposta a tutte le mie domande.",
    "Amarti è come leggere pagine scritte con inchiostro d'amore.",
    "Sei l'armonia perfetta in ogni nota della mia esistenza.",
    "Nel tuo abbraccio trovo la tenerezza che mi completa.",
    "Il tuo amore è come una poesia che danza nel vento.",
    "Amarti è come riscoprire il significato della felicità.",
    "Sei la luce che illumina ogni parte oscura di me.",
    "Nel calore dei tuoi baci trovo la dolcezza dell'amore.",
    "Il tuo sorriso è il riflesso del sole nel mio cielo.",
    "Amarti è come seguire una stella in un cielo senza fine.",
    "Sei la chiave che apre il mio cuore e la mia anima.",
    "Il tuo abbraccio è la protezione che mi fa sentire al sicuro.",
    "Amarti è come immergersi in un oceano di emozioni.",
    "Sei il sogno che non voglio mai svegliarmi da vivere.",
    "Nel riflesso dei tuoi occhi vedo il nostro futuro.",
    "Il tuo amore è come un fuoco che riscalda ogni parte di me.",
    "Amarti è come scrivere una storia d'amore senza fine.",
    "Sei la melodia che canta nel mio cuore ogni giorno.",
    "Nel tuo abbraccio trovo il rifugio dai tormenti del mondo.",
    "Il tuo sorriso è il segreto della felicità che cerco.",
    "Amarti è come trovare un tesoro inaspettato nella vita.",
    "Sei la luce che illumina la via verso il mio cuore.",
    "Nel tuo amore trovo la forza per affrontare ogni sfida.",
    "Il tuo abbraccio è la protezione che allontana ogni paura.",
    "Amarti è come leggere le pagine più belle della mia storia.",
    "Sei il mio compagno di viaggio in questa avventura chiamata amore.",
    "Nel calore del tuo abbraccio trovo il mio rifugio sicuro.",
    "Il tuo amore è la melodia che suona dolcemente nella mia mente.",
    "Amarti è come trovare la chiave del mio cuore smarrita.",
    "Sei il sole che splende nei giorni grigi della mia vita.",
    "Nel riflesso dei tuoi occhi vedo il futuro che desidero.",
    "Il tuo sorriso è la luce che illumina i miei pensieri.",
    "Amarti è come vivere in un mondo fatto solo di emozioni.",
    "Sei il mio sogno che è diventato realtà, la mia realtà più bella.",
    "Nel tuo amore trovo la gioia che rende ogni giorno speciale.",
    "Il tuo abbraccio è il calore che scaccia via ogni freddo.",
    "Amarti è come leggere le parole più dolci scritte nel vento.",
    "Sei la melodia che risuona costante nella mia anima.",
    "Il tuo amore è il sole che scalda ogni angolo del mio cuore.",
    "Amarti è come sentire una dolce melodia nel silenzio della notte.",
    "Sei il mio faro luminoso nelle notti buie dell'esistenza.",
    "Nel tuo abbraccio trovo rifugio dalla tempesta dei pensieri.",
    "Il tuo sorriso è il segreto che illumina i giorni più grigi.",
    "Amarti è come scrivere una canzone senza fine nell'anima.",
    "Sei il miracolo che rende la mia vita un'opera d'arte.",
    "Nel calore dei tuoi baci trovo la dolcezza dell'amore eterno.",
    "Il tuo amore è l'ancora che mi tiene saldo in ogni mare agitato.",
    "Amarti è come leggere un libro di emozioni scritte con il cuore.",
    "Sei la poesia che danza nel vento della nostra storia d'amore.",
    "Nel riflesso dei tuoi occhi vedo il destino che voglio percorrere."
];

let pearls = [
  "Il tuo sorriso illumina ogni mio giorno.",
  "Ogni battito del mio cuore sussurra il tuo nome.",
  "Sei il mio primo pensiero al mattino.",
  "Con te, ogni momento è speciale.",
  "Sei il sogno più bello della mia vita.",
  "Nel tuo abbraccio trovo la mia casa.",
  "Non c'è giorno in cui non ti pensi.",
  "Sei la mia stella nei cieli bui.",
  "Amarti è la mia missione nella vita.",
  "Ogni tuo sguardo mi scalda il cuore.",
  "Nel tuo sorriso trovo la mia pace.",
  "Sei la melodia che non smette di incantarmi.",
  "Con te, il tempo sembra fermarsi.",
  "I tuoi occhi sono il mio rifugio.",
  "Sei il mio arcobaleno dopo ogni tempesta.",
  "Ogni bacio con te è magia pura.",
  "Sei l'essenza della mia felicità.",
  "Nel tuo amore ho trovato la mia forza.",
  "Ogni strada mi porta al tuo cuore.",
  "Sei la luce che guida i miei passi.",
  "Amarti è come respirare, naturale e vitale.",
  "Sei la poesia che colora la mia vita.",
  "Senza di te, nulla avrebbe senso.",
  "Il tuo amore mi rende migliore ogni giorno.",
  "Sei la fiamma che tiene vivo il mio cuore.",
  "In ogni sorriso vedo la tua dolcezza.",
  "Sei il mio rifugio nei giorni di tempesta.",
  "Con te, ogni sogno diventa realtà.",
  "Il tuo amore è il mio dono più prezioso.",
  "Ogni tuo abbraccio è pura felicità.",
  "Sei l'inizio e la fine di ogni mio pensiero.",
  "Nei tuoi occhi trovo l'infinito.",
  "Il tuo amore è la mia più grande fortuna.",
  "Ogni respiro è pieno di te.",
  "Sei la stella più brillante del mio universo.",
  "Nel tuo cuore ho trovato il mio posto.",
  "Ogni tua carezza è una promessa d'eternità.",
  "Sei il sole che illumina i miei giorni.",
  "Amarti è il viaggio più bello della mia vita.",
  "Sei il mio angelo custode in terra.",
  "Con te ogni momento è un'avventura.",
  "Ogni tuo sorriso rende la mia vita più dolce.",
  "Il tuo amore è la mia forza più grande.",
  "Nei tuoi occhi vedo il mio futuro.",
  "Sei la pace che calma la mia anima.",
  "Ogni giorno con te è un regalo unico.",
  "Il tuo amore è la mia ispirazione costante.",
  "Sei la mia felicità senza fine.",
  "Ogni tuo bacio mi porta in paradiso.",
  "Sei il mio porto sicuro, sempre.",
  "Il tuo amore è la mia bussola nella vita.",
  "Ogni tuo abbraccio mi fa sentire invincibile.",
  "Sei il battito del mio cuore, costante e vero.",
  "Il tuo amore è la mia poesia preferita.",
  "Con te, tutto è possibile e magico.",
  "Sei il mio rifugio nei giorni difficili.",
  "Ogni tua parola è una melodia per il mio cuore.",
  "Sei il motivo per cui sorrido ogni giorno.",
  "Il tuo amore è la mia guida nei momenti bui.",
  "Ogni istante con te vale una vita intera.",
  "Sei il mio tutto, sempre e per sempre.",
  "Nel tuo amore ho trovato il mio paradiso.",
  "Ogni giorno con te è una benedizione.",
  "Sei il mio sogno diventato realtà.",
  "Ogni passo che faccio è per raggiungerti.",
  "Sei il mio tesoro più prezioso.",
  "Nel tuo amore ho trovato la mia casa.",
  "Ogni respiro mi ricorda quanto ti amo.",
  "Sei la mia ragione di vita, ogni giorno.",
  "Con te, il mondo è un posto migliore.",
  "Sei la mia anima gemella, il mio destino.",
  "Il tuo amore è il mio dono più grande.",
  "Ogni momento con te è pura gioia.",
  "Sei la mia serenità in mezzo al caos.",
  "Il tuo sorriso è la mia più grande felicità.",
  "Ogni tuo abbraccio è il mio posto felice.",
  "Sei la mia musa, la mia ispirazione eterna.",
  "Con te, ogni giorno è un'avventura.",
  "Ogni notte sogno il tuo dolce volto.",
  "Sei la mia stella, sempre luminosa.",
  "Il tuo amore è la mia vera ricchezza.",
  "Ogni tuo bacio accende il mio cuore.",
  "Sei la mia gioia, oggi e sempre.",
  "Nel tuo amore ho trovato la mia pace.",
  "Ogni istante con te è un miracolo.",
  "Sei la mia isola di felicità nel mare della vita.",
  "Ogni tua risata riempie il mio cuore di gioia.",
  "Sei il mio orizzonte infinito.",
  "Amarti è il mio privilegio più grande.",
  "Sei la scintilla che accende la mia vita.",
  "Ogni tua parola è musica per le mie orecchie.",
  "Nel tuo sguardo trovo la mia eternità.",
  "Sei il faro che illumina il mio cammino.",
  "Ogni momento lontano da te è un'eternità.",
  "Sei il mio destino scritto nelle stelle.",
  "Ogni tuo tocco è magia pura.",
  "Sei il mio sole anche nei giorni più bui.",
  "Con te, ho imparato cosa significa amare davvero.",
  "Ogni tua carezza è una promessa di amore eterno.",
  "Sei la chiave che apre il mio cuore.",
  "Nel tuo amore trovo il mio coraggio.",
  "Ogni sorriso che mi doni è un tesoro.",
  "Sei il mio rifugio sicuro.",
  "Ogni tuo abbraccio è una carezza per l'anima.",
  "Sei la mia primavera eterna.",
  "Nel tuo amore ho scoperto la mia vera essenza.",
  "Ogni tuo bacio è il mio paradiso personale.",
  "Sei la mia pace dopo ogni battaglia.",
  "Ogni giorno con te è un nuovo inizio.",
  "Sei il mio sogno che si avvera ogni mattina.",
  "Ogni tuo sguardo racconta una storia d'amore.",
  "Sei il mio arco di colori dopo la pioggia.",
  "Ogni attimo con te è un dono prezioso.",
  "Sei il mio per sempre, oggi e domani.",
  "Nel tuo abbraccio il mondo svanisce.",
  "Ogni tua parola riscalda la mia anima.",
  "Sei il mio universo in un singolo sorriso.",
  "Ogni passo che faccio è verso il tuo amore.",
  "Sei la mia speranza in ogni momento difficile.",
  "Ogni tua risata illumina il mio cuore.",
  "Sei la mia stella cadente, un desiderio avverato.",
  "Nel tuo amore trovo la mia libertà.",
  "Ogni giorno con te è pura magia.",
  "Sei la mia luce quando tutto è buio.",
  "Ogni tuo gesto è un atto d'amore puro.",
  "Sei la mia luna nei cieli più bui.",
  "Ogni volta che ti vedo, il mio cuore si ferma.",
  "Sei la mia costante in un mondo di cambiamenti.",
  "Con te, tutto diventa possibile.",
  "Ogni tuo respiro mi ricorda il significato della vita.",
  "Sei la mia calma nella tempesta.",
  "Non esiste un luogo migliore del tuo cuore.",
  "Sei la mia ispirazione per sognare in grande.",
  "Ogni tuo abbraccio cura le ferite della mia anima.",
  "Sei il mio nord quando sono perso.",
  "Nel tuo amore trovo la vera felicità.",
  "Ogni tuo sorriso è una promessa di domani migliori.",
  "Sei il mio tramonto e il mio nuovo giorno.",
  "Ogni parola che dici è musica per il mio cuore.",
  "Sei il mio unico, il mio eterno.",
  "Ogni momento con te è una storia d'amore unica.",
  "Sei il mio porto sicuro in un mare in tempesta.",
  "Nel tuo amore trovo il mio vero io.",
  "Ogni tua carezza accende la mia anima.",
  "Sei la mia fonte infinita di gioia.",
  "Ogni attimo con te è pura meraviglia.",
  "Sei il mio ponte tra sogno e realtà.",
  "Ogni tuo sguardo mi racconta un amore eterno.",
  "Sei la mia fiamma nei momenti più freddi.",
  "Nel tuo sorriso trovo il mio rifugio.",
  "Ogni tuo bacio è un viaggio tra le stelle.",
  "Sei il mio primo pensiero ogni alba.",
  "Ogni tuo gesto parla di amore sincero.",
  "Sei la mia casa, ovunque tu sia.",
  "Nel tuo amore ho trovato la mia libertà.",
  "Ogni tuo respiro mi fa sentire vivo.",
  "Sei la mia metà mancante, perfettamente incastrata.",
  "Ogni strada che percorro mi riporta a te.",
  "Sei la luce che illumina il mio cammino.",
  "Nel tuo abbraccio trovo tutto ciò che serve alla mia anima.",
  "Ogni tuo sguardo è come un’alba su un mondo nuovo.",
  "Sei il mio rifugio e la mia forza.",
  "Ogni tua risata rende più leggero il mio cuore.",
  "Sei il mio sogno più prezioso.",
  "Ogni istante lontano da te è un’eternità.",
  "Sei il mio arcobaleno dopo ogni pioggia.",
  "Ogni passo verso di te è il viaggio di una vita.",
  "Sei il mio presente e il mio futuro.",
  "Ogni tua parola mi dà forza e speranza.",
  "Sei il mio cielo stellato in una notte senza fine.",
  "Ogni tuo sorriso mi riempie di gioia autentica.",
  "Sei il mio tramonto preferito, dolce e infinito.",
  "Ogni momento con te è una favola da raccontare.",
  "Sei la mia poesia preferita scritta dal destino.",
  "Nel tuo amore ho trovato la mia eternità.",
  "Ogni tuo abbraccio cancella ogni mia paura.",
  "Sei la mia scintilla nei giorni più grigi.",
  "Ogni giorno con te è un capitolo perfetto.",
  "Sei la mia ispirazione per tutto ciò che faccio.",
  "Ogni tuo bacio è un viaggio nel paradiso.",
  "Sei il mio miracolo quotidiano.",
  "Ogni tuo gesto mi riempie di gratitudine.",
  "Sei la melodia che il mio cuore non smette di cantare.",
  "Ogni tuo sguardo accende una luce nella mia anima.",
  "Sei la mia pace, il mio porto sicuro.",
  "Ogni istante con te vale più di mille vite.",
  "Sei la mia roccia e il mio rifugio.",
  "Ogni tua carezza mi fa sentire amato come mai prima.",
  "Sei il mio cielo sereno dopo ogni tempesta.",
  "Ogni tuo sorriso trasforma la mia giornata.",
  "Sei il mio amore, la mia casa, la mia vita.",
  "Ogni tua parola mi fa credere nel vero amore.",
  "Sei il mio fiore che sboccia in ogni stagione.",
  "Ogni tua risata è musica per la mia anima.",
  "Sei il mio tutto in un mondo di niente.",
  "Ogni tuo abbraccio mi fa dimenticare il resto.",
  "Sei la mia forza nei momenti di debolezza.",
  "Ogni tuo bacio è un dono che custodisco nel cuore.",
  "Sei il mio raggio di sole in un mondo di ombre.",
  "Ogni passo con te è un passo verso la felicità.",
  "Sei il mio inizio e la mia fine.",
  "Ogni giorno con te è una promessa mantenuta.",
  "Sei il mio sogno che vive nella realtà.",
  "Ogni tuo sguardo mi dà la certezza di essere a casa.",
  "Sei il mio conforto nei momenti di tempesta.",
  "Ogni tuo sorriso mi dà speranza.",
  "Sei la mia anima gemella, perfettamente incastrata.",
  "Ogni attimo senza di te è incompleto.",
  "Sei il mio amore eterno, oggi e per sempre.",
  "La tua voce è la melodia che dà ritmo alla mia vita.",
  "Ogni tuo respiro mi riempie di pace e serenità.",
  "Nel tuo sorriso trovo la forza per affrontare tutto.",
  "Sei il mio tramonto dorato in un cielo infinito.",
  "Il tuo tocco trasforma ogni momento in pura poesia.",
  "Ogni giorno con te mi insegna l'essenza dell'amore.",
  "Sei il mio coraggio quando il mondo sembra crollare.",
  "Nel tuo amore trovo la mia ispirazione quotidiana.",
  "Ogni tuo sguardo accende una fiamma nel mio cuore.",
  "Sei la mia ombra nei momenti di sole e di buio.",
  "Ogni tuo abbraccio è un rifugio sicuro per la mia anima.",
  "Sei la melodia che accompagna ogni mio pensiero.",
  "Nel tuo cuore trovo il mio posto felice.",
  "Ogni momento insieme è una pagina del nostro libro d’amore.",
  "Sei la stella polare che guida il mio viaggio.",
  "Il tuo amore è il colore che dipinge i miei giorni.",
  "Ogni tuo gesto parla più di mille parole.",
  "Sei il mio abbraccio caldo nei giorni freddi.",
  "Con te, ogni giorno diventa una nuova avventura.",
  "Ogni tua parola è una promessa di felicità.",
  "Sei il mio arcobaleno di speranza dopo ogni tempesta.",
  "Ogni tuo bacio è un ponte tra le nostre anime.",
  "Sei la linfa che nutre il mio cuore e la mia mente.",
  "Ogni giorno con te è un sogno che continua.",
  "Sei il mio miracolo quotidiano, semplice e meraviglioso.",
  "Nel tuo amore trovo tutto ciò di cui ho bisogno.",
  "Ogni tuo sorriso rende il mondo un posto migliore.",
  "Sei il mio faro quando sono perso nel buio.",
  "Ogni tua carezza mi ricorda che sono vivo.",
  "Sei la mia pace nei momenti di caos.",
  "Ogni tuo abbraccio è un balsamo per la mia anima.",
  "Sei il mio motivo per credere nei miracoli.",
  "Nel tuo amore ho trovato il significato della vita.",
  "Ogni tuo sguardo illumina i miei giorni più bui.",
  "Sei la mia stella che splende sempre, ovunque io sia.",
  "Ogni passo accanto a te mi porta verso la felicità.",
  "Sei il mio rifugio quando tutto il resto svanisce.",
  "Ogni attimo con te è un dono inestimabile.",
  "Sei la mia oasi nel deserto della vita.",
  "Ogni giorno con te rinnova il mio amore.",
  "Sei la mia roccia su cui costruire ogni sogno.",
  "Nel tuo abbraccio trovo il significato dell’amore eterno.",
  "Ogni tuo sorriso è un invito a vivere meglio.",
  "Sei la luce che rende ogni momento indimenticabile.",
  "Ogni tua parola è una poesia dedicata alla mia anima.",
  "Sei la mia quiete dopo ogni tempesta.",
  "Quando mi stringi, il tempo sembra fermarsi.",
  "La tua voce è il mio suono preferito.",
  "Mi basta vederti per sapere che tutto andrà bene.",
  "Il tuo amore è il vento che gonfia le vele della mia vita.",
  "Ho trovato un tesoro nel tuo cuore.",
  "Ogni sogno che ho si intreccia con te.",
  "Sorrido di più da quando sei nella mia vita.",
  "La bellezza del mondo non si avvicina alla tua.",
  "Vorrei catturare ogni momento con te per sempre.",
  "La tua risata rende la mia giornata perfetta.",
  "Mi completi in modi che non pensavo possibili.",
  "Il tuo amore è un viaggio che non finisce mai.",
  "Trovo un mondo nuovo ogni volta che ti guardo.",
  "Non ho bisogno di nulla quando sei accanto a me.",
  "Sei il battito che tiene in vita il mio cuore.",
  "Nessun posto è più bello di quello accanto a te.",
  "La tua felicità è tutto ciò che desidero.",
  "Tu rendi ogni giornata un piccolo miracolo.",
  "Non sapevo cosa fosse l’amore prima di te.",
  "Camminare con te è come vivere in una fiaba.",
  "Ogni volta che ti guardo, mi innamoro di nuovo.",
  "Le stelle sembrano più luminose da quando sei qui.",
  "Il tuo amore ha trasformato ogni mio dubbio in certezza.",
  "In un mare di volti, il tuo è l’unico che conta.",
  "Il mondo è più bello visto dai tuoi occhi.",
  "Tu sei la calma che placa ogni mia tempesta.",
  "Amarti è come trovare la strada di casa.",
  "Nelle tue mani, ho trovato la mia felicità.",
  "Sei il filo che tiene insieme i pezzi del mio cuore.",
  "Con te, il domani non fa paura.",
  "Ogni momento passato con te è il mio preferito.",
  "Mi perdo nelle tue parole, e non voglio ritrovarmi.",
  "L’amore ha preso forma quando ti ho incontrato.",
  "La tua luce illumina anche i miei giorni più scuri.",
  "Vorrei che il tempo si fermasse quando sei con me.",
  "Tutto ha più senso quando siamo insieme.",
  "Tu sei il dono che non smetto mai di scartare.",
  "Ogni battito del mio cuore porta il tuo nome.",
  "Le tue mani hanno il potere di guarire ogni mia ferita.",
  "L’universo mi ha portato il suo miracolo: te.",
  "Il tuo sorriso è la mia destinazione preferita.",
  "Quando rido con te, il mondo sembra più leggero.",
  "Tu sei la ragione per cui credo nei lieto fine.",
  "Sei il primo capitolo della mia storia d’amore.",
  "Amarti è facile come respirare.",
  "Quando sei lontano, il mondo perde il suo colore.",
  "La mia felicità si riflette nei tuoi occhi.",
  "Il tuo amore è la risposta a tutte le mie domande.",
  "Tu sei la scintilla che accende il mio mondo.",
  "Con te, ogni strada sembra quella giusta.",
  "Quando chiudo gli occhi, vedo solo te.",
  "Il tuo amore mi insegna la bellezza della semplicità.",
  "Nelle tue mani, il mio cuore si sente al sicuro.",
  "Sei il mio arcobaleno nei giorni più grigi.",
  "L’amore vero ha preso vita quando ti ho incontrato.",
  "Camminare al tuo fianco rende ogni passo speciale.",
  "La tua presenza trasforma ogni momento in un ricordo eterno.",
  "Nel tuo sorriso c’è un mondo che voglio esplorare.",
  "Tu sei la poesia scritta nel mio destino.",
  "Ogni tuo sguardo racconta un amore senza fine.",
  "Con te, ogni giornata è un regalo prezioso.",
  "Il tuo abbraccio è il luogo dove il mio cuore si riposa.",
  "Quando sei accanto a me, tutto sembra possibile.",
  "Il tuo amore è la risposta a ogni mio dubbio.",
  "Con te, non ho bisogno di nient’altro.",
  "Il tuo tocco è una melodia che calma ogni tempesta.",
  "Quando mi guardi, il tempo si ferma.",
  "Sei il mio tramonto preferito, delicato e profondo.",
  "Mi basta un tuo sorriso per dimenticare tutto il resto.",
  "Tu sei il cuore che batte al ritmo della mia vita.",
  "Il tuo amore è l’energia che alimenta ogni mio sogno.",
  "Ogni giorno accanto a te è un capitolo perfetto.",
  "Tu sei il respiro che dà vita alla mia anima.",
  "Amarti è la mia missione più dolce e pura.",
  "La tua risata è il suono più bello che abbia mai sentito.",
  "Quando ti stringo, trovo la pace che cerco da sempre.",
  "Il tuo amore è l’inizio e la fine di ogni mia giornata.",
  "Tu sei il cielo sereno dopo ogni tempesta.",
  "Con te, ogni ombra si trasforma in luce.",
  "Sei la mia fonte infinita di gioia e ispirazione.",
  "La tua presenza rende ogni luogo casa mia.",
  "Quando ti vedo, dimentico tutto il resto.",
  "Il tuo amore mi guida anche nei giorni più scuri.",
  "Tu sei il mio tutto in un mondo di niente.",
  "Ogni istante accanto a te è un momento da custodire.",
  "Tu sei l’alba di cui il mio cuore ha sempre avuto bisogno.",
  "Con te, ogni sogno sembra a portata di mano.",
  "Tu sei il mio futuro, il mio presente e il mio passato.",
  "La tua dolcezza rende ogni momento indimenticabile.",
  "Non c’è nulla che desideri più del tuo amore.",
  "Il tuo amore è la risposta alle mie preghiere.",
  "Tu sei la fiamma che tiene acceso il mio spirito.",
  "Ogni giorno inizia meglio quando sei nei miei pensieri.",
  "Con te, ho scoperto la vera essenza della felicità.",
  "Tu sei la melodia che accompagna ogni mio passo.",
  "Nel tuo sguardo trovo un universo di possibilità.",
  "Ogni sorriso che mi regali è un tesoro prezioso.",
  "Con te, tutto è più semplice, più vero.",
  "Sei l’abbraccio che avvolge ogni mia paura.",
  "La tua voce è il balsamo che calma la mia anima.",
  "Con te, il tempo non conta, esiste solo l’amore.",
  "Sei la melodia del mio cuore.",
  "Il tuo amore è il mio regalo più grande.",
  "Mi perdo nel calore del tuo sguardo.",
  "Sei il mio sogno diventato realtà.",
  "La tua risata è la mia felicità.",
  "Con te, il tempo vola via.",
  "Ogni giorno con te è una benedizione.",
  "Il tuo amore è la mia ispirazione.",
  "Non riesco a smettere di pensarti.",
];
